"""Adiciona modelo DoctorRecord

Revision ID: 41fa9ae37255
Revises:
Create Date: 2025-09-30 22:06:17.342947

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "41fa9ae37255"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "doctor_records",
        sa.Column("uid", sa.VARCHAR(length=50), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("crm", sa.VARCHAR(length=20), nullable=False),
        sa.Column("specialty", sa.VARCHAR(length=100), nullable=False),
        sa.Column("email", sa.VARCHAR(length=100), nullable=False),
        sa.Column("phone", sa.VARCHAR(length=20), nullable=False),
        sa.Column("status", sa.INTEGER(), nullable=False),
        sa.Column("hospital_affiliation", sa.VARCHAR(length=200), nullable=True),
        sa.Column("office_address", sa.VARCHAR(length=200), nullable=True),
        sa.Column("date_created", sa.TIMESTAMP(), nullable=False),
        sa.Column("date_updated", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("uid"),
    )

    op.create_table(
        "pacient_records",
        sa.Column("uid", sa.VARCHAR(length=50), nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), nullable=False),
        sa.Column("dateofbirth", sa.DateTime(), nullable=False),
        sa.Column("gender", sa.INTEGER(), nullable=False),
        sa.Column("email", sa.VARCHAR(length=100), nullable=False),
        sa.Column("phone", sa.VARCHAR(length=20), nullable=False),
        sa.Column("status", sa.INTEGER(), nullable=False),
        sa.Column("date_created", sa.TIMESTAMP(), nullable=False),
        sa.Column("date_updated", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("uid"),
    )

    op.create_table(
        "users",
        sa.Column("uid", sa.VARCHAR(length=50), nullable=False),
        sa.Column("username", sa.VARCHAR(length=50), nullable=False),
        sa.Column("email", sa.VARCHAR(length=100), nullable=False),
        sa.Column("password_hash", sa.VARCHAR(length=150), nullable=False),
        sa.Column("date_created", sa.TIMESTAMP(), nullable=False),
        sa.Column("date_updated", sa.TIMESTAMP(), nullable=False),
        sa.Column("role", sa.VARCHAR(length=50), nullable=False),
        sa.Column("is_verified", sa.BOOLEAN(), nullable=False),
        sa.PrimaryKeyConstraint("uid"),
    )

    op.create_table(
        "medical_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.VARCHAR(length=50), nullable=False),
        sa.Column("doctor_id", sa.VARCHAR(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("medications", sa.JSON(), nullable=True),
        sa.Column("date_requested", sa.DateTime(), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=False),
        sa.Column("date_updated", sa.DateTime(), nullable=False),
        sa.Column("blockchain_tx_id", sa.String(length=100), nullable=True),
        sa.Column("blockchain_verified", sa.Boolean(), nullable=True),
        sa.Column("record_hash", sa.String(length=64), nullable=True),
        sa.Column("file_url", sa.String(length=255), nullable=True),
        sa.Column("file_hash", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctor_records.uid"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["pacient_records.uid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("doctor_records")
    op.drop_table("pacient_records")
    op.drop_table("medical_records")
    op.drop_table("users")
    # ### end Alembic commands ###
